SPECFILE = python-etcd.spec
PACKAGE=$(shell grep -s '^Name'    $(SPECFILE) | sed -e 's/Name: *//')
VERSION=$(shell grep -s '^Version' $(SPECFILE) | sed -e 's/Version: *//')
PKGNAME=$(PACKAGE)-$(VERSION)
TARFILE=$(PKGNAME).tar.gz

all:
	mkdir $(PKGNAME)
	ls | grep -v -E '$(PKGNAME)|\.git' | xargs cp -rt $(PKGNAME)
	tar cvzf $(TARFILE) $(PKGNAME)
	rm -r $(PKGNAME)

clean:
	rm $(TARFILE)
